apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-runtime
  namespace: accordlock-demo
  labels:
    accordlock.io/profile: deploy-eks-image-v1
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: accordlock-demo
  labels:
    accordlock.io/profile: deploy-eks-image-v1
  annotations:
    accordlock.io/transaction-id: unset
    accordlock.io/authorization-id: unset
    accordlock.io/operation-hash: unset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      automountServiceAccountToken: false
      serviceAccountName: payments-runtime
      containers:
        - name: app
          image: docker.io/library/nginx@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 1
            periodSeconds: 2
