[package]
name = "accordlock-terminal-witness"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
minicbor.workspace = true
thiserror.workspace = true
uuid.workspace = true
accordlock-protocol = { path = "../accordlock-protocol" }

[lints]
workspace = true
