apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.json
  - service-account.json
  - config-map.json
  - deployment.json
  - service.json
  - pod-disruption-budget.json
  - validating-webhook-configuration.json
