[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'postgres-common.ps1')

$versionFile = Join-Path $script:AccordLockPostgresData 'PG_VERSION'
if (Test-Path -LiteralPath $versionFile -PathType Leaf) {
    $version = (Get-Content -LiteralPath $versionFile -Raw).Trim()
    if ($version -ne '17') {
        throw "Existing local cluster is PostgreSQL $version, expected 17"
    }
    Write-Output "PASS postgres_init existing_cluster=$script:AccordLockPostgresData version=$version"
    exit 0
}

if (Test-Path -LiteralPath $script:AccordLockPostgresData) {
    $entries = @(Get-ChildItem -LiteralPath $script:AccordLockPostgresData -Force)
    if ($entries.Count -ne 0) {
        throw "Refusing to initialize non-empty directory without PG_VERSION: $script:AccordLockPostgresData"
    }
} else {
    New-Item -ItemType Directory -Path $script:AccordLockPostgresData -Force | Out-Null
}

$initdb = Find-AccordLockPostgresCommand -Name 'initdb'
Invoke-AccordLockNative -Command $initdb -Arguments @(
    '-D', $script:AccordLockPostgresData,
    '--username=postgres',
    '--auth-local=trust',
    '--auth-host=trust',
    '--encoding=UTF8',
    '--no-locale'
)

$configuration = Join-Path $script:AccordLockPostgresData 'postgresql.conf'
Add-Content -LiteralPath $configuration -Encoding utf8 -Value @"

# AccordLock disposable local test cluster. Generated by infra/local/postgres/init.ps1.
listen_addresses = '127.0.0.1'
port = $script:AccordLockPostgresPort
fsync = on
synchronous_commit = on
full_page_writes = on
"@

Write-Output "PASS postgres_init new_cluster=$script:AccordLockPostgresData version=17 auth=trust_loopback_only"
Write-Output 'BOUNDARY disposable local test data only; do not expose this trust-authenticated cluster'
